const https = require('https');

// ============================================================
// IN-HOUSE AI DETECTOR v6
// Hybrid approach matching frontier platforms:
// 1. LLM-as-classifier (like GPTZero's fine-tuned model, but using GPT-4o-mini)
// 2. Statistical signals (burstiness, vocabulary, patterns) as secondary
// 
// Frontier platforms (GPTZero, Originality.ai) use fine-tuned RoBERTa classifiers.
// We approximate by using GPT-4o-mini as a zero-shot classifier + statistical features.
// ============================================================

const DETECTOR_PROMPT = `You are an expert AI-generated text detector, similar to GPTZero or Originality.ai. 

Analyze the following text and determine if it was written by a human or generated by AI.

Evaluate these signals (this is what frontier detectors measure):

1. PERPLEXITY: How predictable is the word choice? AI text uses statistically "safe", expected words. Human text has more surprising, creative, or idiosyncratic word choices.

2. BURSTINESS: How varied are sentence lengths and structures? Human writing alternates between short punchy sentences and longer complex ones. AI tends toward uniform rhythm.

3. TOKEN PROBABILITY PATTERNS: Does the text cluster around high-probability word choices that an LLM would pick? Or does it contain low-probability, human-like deviations?

4. AI FINGERPRINTS: Look for telltale AI patterns:
   - "In the rapidly evolving...", "Let's dive in", "It's worth noting"
   - Overly smooth transitions (Furthermore, Moreover, Consequently)
   - Generic hedging ("it tends to", "in most scenarios")
   - Perfect parallel structure across multiple points
   - Uniform paragraph lengths
   - Lack of personal voice, colloquialisms, or imperfections

5. HUMAN MARKERS: Look for signs of genuine human authorship:
   - Personal anecdotes, specific names/places/dates
   - Colloquial language, slang, cultural references
   - Inconsistent formatting or style within the piece
   - Sentence fragments, starting with "And" or "But"
   - Genuine opinion/emotion (not hedged corporate-speak)
   - Typos, self-corrections, parenthetical asides

IMPORTANT: Be STRICT. Match the strictness of GPTZero (the industry standard). GPTZero flags even well-written AI text at 100% AI confidence. Your scoring should match:
- Pure AI text (ChatGPT/Claude default output): score 0-15
- AI text with light editing: score 15-30  
- Heavily humanized AI text: score 30-50
- Mix of human and AI: score 50-70
- Genuine human writing (may still have some uniform patterns): score 70-85
- Clearly human with strong personal voice: score 85-100

Look for these AI giveaways even in "humanized" text:
- Suspiciously smooth flow from point to point
- Every paragraph roughly the same length
- Lack of genuine personal experience or specific anecdotes
- Perfect grammar throughout (humans make small errors)
- Overly balanced "on one hand / on the other hand" structures
- Generic analogies instead of oddly specific ones

Respond with ONLY a JSON object (no markdown, no explanation):
{
  "score": <0-100, where 0=definitely AI, 100=definitely human>,
  "confidence": <0-100, how confident you are>,
  "signals": {
    "perplexity": <"low"|"medium"|"high">,
    "burstiness": <"low"|"medium"|"high">,
    "ai_patterns": <number of AI patterns found>,
    "human_markers": <number of human markers found>
  },
  "flagged_sentences": [<list of sentences that look most AI-generated>],
  "reasoning": "<1-2 sentence explanation>"
}`;

/**
 * Statistical signals (fast, no API call)
 */
function splitSentences(text) {
  return text.split(/(?<=[.!?])\s+|\n\n+/).map(s => s.trim()).filter(s => s.length > 10);
}

function tokenize(text) {
  return text.toLowerCase().replace(/[^a-z0-9\s'-]/g, ' ').split(/\s+/).filter(w => w.length > 1);
}

function calcBurstiness(values) {
  if (values.length < 2) return 0;
  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  if (mean === 0) return 0;
  const variance = values.reduce((sum, v) => sum + (v - mean) ** 2, 0) / values.length;
  return Math.round((Math.sqrt(variance) / mean) * 1000) / 1000;
}

function vocabRichness(words) {
  if (words.length < 20) return { ttr: 0.5 };
  const unique = new Set(words);
  return { ttr: Math.round((unique.size / words.length) * 1000) / 1000 };
}

const AI_PATTERNS = [
  /\bin (?:the|today's) (?:rapidly |ever-)?(?:evolving|changing) (?:landscape|world)/i,
  /\blet's (?:dive|delve|explore|unpack)/i,
  /\bit'?s worth noting/i,
  /\bgame[- ]changer/i,
  /\blever(?:age|aging)/i,
  /\bcomprehensive (?:guide|overview|look)/i,
  /\bstream ?line/i,
  /\brobust (?:solution|framework|system|platform)/i,
  /\bcutting[- ]edge/i,
  /\bunprecedented/i,
  /\btransformative/i,
  /\bseamless(?:ly)?/i,
  /\bholistic approach/i,
  /\bin conclusion/i,
  /\bfurthermore,/i,
  /\bmoreover,/i,
  /\bconsequently,/i,
  /\bnevertheless,/i,
  /\bundoubtedly/i,
  /\bempowe?r(?:ing|s)?/i,
  /\bfoster(?:ing|s)? (?:innovation|collaboration|growth)/i,
  /\bnavigate (?:the|this)/i,
  /\bparadigm shift/i,
  /\bin today's (?:world|age|era|digital)/i,
  /\bkey takeaway/i,
];

function countAIPatterns(text) {
  return AI_PATTERNS.reduce((c, p) => c + (p.test(text) ? 1 : 0), 0);
}

/**
 * LLM-as-classifier: Ask GPT-4o-mini to score the text
 */
function llmClassify(text, apiKey, model = 'anthropic/claude-opus-4-6') {
  // Truncate to ~2000 words to keep costs low
  const truncated = text.split(/\s+/).slice(0, 2000).join(' ');

  const body = JSON.stringify({
    model,
    messages: [
      { role: 'system', content: DETECTOR_PROMPT },
      { role: 'user', content: truncated }
    ],
    temperature: 0,
    max_tokens: 500,
  });

  return new Promise((resolve, reject) => {
    const url = new URL('https://openrouter.ai/api/v1/chat/completions');
    const req = https.request(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body),
      },
      timeout: 30000,
    }, res => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        if (res.statusCode >= 400) {
          reject(new Error(`OpenAI ${res.statusCode}: ${data.slice(0, 300)}`));
          return;
        }
        try {
          const parsed = JSON.parse(data);
          const content = parsed.choices?.[0]?.message?.content || '{}';
          // Strip markdown code fences if present
          const cleaned = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
          const result = JSON.parse(cleaned);
          resolve(result);
        } catch (e) {
          reject(new Error('Failed to parse LLM classifier response: ' + e.message));
        }
      });
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('LLM classifier timeout')); });
    req.write(body);
    req.end();
  });
}

/**
 * Main detection function
 * Combines LLM classification with statistical signals
 */
async function detect(text, apiKey, options = {}) {
  const model = options.model || 'anthropic/claude-opus-4-6';
  const sentences = splitSentences(text);
  const words = tokenize(text);

  if (words.length < 20) {
    return { score: 50, error: 'Text too short for reliable detection' };
  }

  // ── Statistical signals (instant, free) ──
  const sentLengths = sentences.map(s => s.split(/\s+/).length);
  const lengthBurst = calcBurstiness(sentLengths);
  const vocab = vocabRichness(words);
  const aiPatterns = countAIPatterns(text);

  // ── LLM classification (1 API call) ──
  let llmResult = null;
  try {
    llmResult = await llmClassify(text, apiKey, model);
  } catch (e) {
    // Fall back to stats-only if LLM fails
    llmResult = { score: null, error: e.message };
  }

  // ── Combine scores ──
  const llmScore = typeof llmResult?.score === 'number' ? llmResult.score : null;

  // Statistical score
  let statScore = 50;

  // AI patterns: strongest statistical signal
  if (aiPatterns >= 3) statScore -= 30;
  else if (aiPatterns >= 1) statScore -= 10 * aiPatterns;

  // Burstiness
  if (lengthBurst >= 0.5) statScore += 15;
  else if (lengthBurst <= 0.2) statScore -= 15;

  // Vocab richness
  if (vocab.ttr >= 0.65) statScore += 10;
  else if (vocab.ttr <= 0.45) statScore -= 10;

  statScore = Math.max(0, Math.min(100, statScore));

  // Final score: LLM 70%, Stats 30% (LLM is the primary classifier, stats are secondary)
  const finalScore = llmScore !== null
    ? Math.round(llmScore * 0.7 + statScore * 0.3)
    : statScore;

  return {
    score: Math.max(0, Math.min(100, finalScore)),
    ai_probability: Math.round((100 - finalScore) / 100 * 1000) / 1000,
    human_probability: Math.round(finalScore / 100 * 1000) / 1000,
    llm_score: llmScore,
    stat_score: statScore,
    metrics: {
      vocab_ttr: vocab.ttr,
      length_burstiness: lengthBurst,
      ai_patterns_found: aiPatterns,
      sentence_count: sentences.length,
      word_count: words.length,
    },
    llm_analysis: llmResult?.signals || null,
    reasoning: llmResult?.reasoning || null,
    flagged_sentences: llmResult?.flagged_sentences || [],
    model_used: model,
  };
}

module.exports = { detect, splitSentences, tokenize, vocabRichness, calcBurstiness, countAIPatterns };
