const https = require('https');
const http = require('http');

// ============================================================
// HUMANIZER ENGINE
// Pluggable LLM + AI detection verification loop
// ============================================================

const SYSTEM_PROMPT = `You are a text rewriter. Your ONLY job is to rephrase text using different words and sentence structures while keeping the EXACT same meaning.

ABSOLUTE RULE — MEANING PRESERVATION:
- Every fact, point, claim, number, name, and piece of information in the original MUST appear in your output.
- Do NOT add new ideas, opinions, tangents, examples, or analogies that weren't in the original.
- Do NOT remove any points or information.
- Do NOT change the meaning of anything. If the original says "React Server Components reduce bundle size", your output must say the same thing — just phrased differently.
- Same message. Different words. That is the entire job.

HOW TO REPHRASE (to pass AI detection):

SENTENCE STRUCTURE:
1. Vary sentence lengths. Short ones. Then longer ones that go on for a bit with clauses and asides. Then short again.
2. Use fragments occasionally.
3. Start some sentences with "And", "But", "So", "Because".
4. Drop in a rhetorical question here and there.

WORD CHOICE:
5. Swap words for less predictable synonyms — "important" → "kind of a big deal", "implement" → "wire up".
6. Mix casual and technical language naturally.
7. Occasional filler: "honestly", "basically", "look".
8. Use contractions inconsistently — mix "don't" and "do not".

WHAT NOT TO DO:
9. NEVER use: "It's worth noting", "In today's world", "game-changer", "landscape", "leverage", "comprehensive", "streamline", "robust", "cutting-edge", "delve", "Furthermore", "Moreover", "Consequently", "Nevertheless", "unprecedented", "transformative", "seamlessly", "holistic", "paradigm", "empowering", "fostering innovation", "In conclusion", "key takeaway".
10. NEVER use smooth academic transitions between every paragraph.
11. NEVER write sentences that all hover around the same length.
12. NEVER make the text longer or add fluff.
13. CODE BLOCKS must be returned EXACTLY as-is.

Output ONLY the rewritten text. No explanations.`;

const REWRITE_FLAGGED_PROMPT = `The following sentences were flagged as AI-generated by a classifier.

Rewrite ONLY the flagged sentences. Keep everything else IDENTICAL word for word.

Rules for rewriting flagged sentences:
- SAME exact meaning and information — just different words and sentence structure.
- Use less predictable word choices.
- Vary sentence length — mix short fragments with longer sentences.
- No smooth connectors ("Furthermore", "Additionally").
- Do NOT add new information, opinions, or tangents.

Flagged sentences:
{flagged}

Full text:
{text}

Output the full text with ONLY the flagged sentences rephrased. Everything else unchanged.`;

// ============================================================
// LLM PROVIDERS
// ============================================================

class LLMProvider {
  constructor(config) {
    this.provider = config.provider || 'openrouter';
    this.apiKey = config.apiKey;
    this.model = config.model;
    this.baseUrl = config.baseUrl;

    if (this.provider === 'openrouter') {
      this.model = this.model || 'anthropic/claude-opus-4-6';
      this.baseUrl = this.baseUrl || 'https://openrouter.ai/api';
    } else if (this.provider === 'openai') {
      this.model = this.model || 'gpt-5.2';
      this.baseUrl = this.baseUrl || 'https://api.openai.com';
    } else if (this.provider === 'anthropic') {
      this.model = this.model || 'claude-sonnet-4-20250514';
      this.baseUrl = this.baseUrl || 'https://api.anthropic.com';
    } else if (this.provider === 'custom') {
      if (!this.baseUrl) throw new Error('baseUrl required for custom provider');
      this.model = this.model || 'default';
    }
  }

  async complete(systemPrompt, userPrompt, temperature = 0.8) {
    if (this.provider === 'anthropic') {
      return this._anthropic(systemPrompt, userPrompt, temperature);
    }
    return this._openai(systemPrompt, userPrompt, temperature);
  }

  _openai(systemPrompt, userPrompt, temperature) {
    const body = JSON.stringify({
      model: this.model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature,
      max_tokens: 4096,
    });

    const url = new URL(this.baseUrl + '/v1/chat/completions');
    return this._request(url, body, {
      'Authorization': `Bearer ${this.apiKey}`,
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      if (parsed.error) throw new Error(parsed.error.message || JSON.stringify(parsed.error));
      return parsed.choices?.[0]?.message?.content || '';
    });
  }

  _anthropic(systemPrompt, userPrompt, temperature) {
    const body = JSON.stringify({
      model: this.model,
      max_tokens: 4096,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
      temperature,
    });

    const url = new URL('https://api.anthropic.com/v1/messages');
    return this._request(url, body, {
      'x-api-key': this.apiKey,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      if (parsed.error) throw new Error(parsed.error.message || JSON.stringify(parsed.error));
      return parsed.content?.[0]?.text || '';
    });
  }

  _request(url, body, headers) {
    return new Promise((resolve, reject) => {
      const mod = url.protocol === 'https:' ? https : http;
      const req = mod.request(url, {
        method: 'POST',
        headers: { ...headers, 'Content-Length': Buffer.byteLength(body) },
        timeout: 120000,
      }, res => {
        let data = '';
        res.on('data', c => data += c);
        res.on('end', () => {
          if (res.statusCode >= 400) {
            reject(new Error(`LLM API error ${res.statusCode}: ${data.slice(0, 500)}`));
          } else {
            resolve(data);
          }
        });
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('LLM request timeout')); });
      req.write(body);
      req.end();
    });
  }
}

// ============================================================
// AI DETECTION
// Supports: gptzero, sapling
// ============================================================

class AIDetector {
  constructor(config = {}) {
    this.provider = config.provider || 'gptzero';
    this.apiKey = config.apiKey;
    this.model = config.model;
  }

  async detect(text) {
    if (this.provider === 'inhouse') return this._inhouse(text);

    if (!this.apiKey) {
      return { score: 0, human_score: 1, sentences: [], skipped: true };
    }

    if (this.provider === 'gptzero') return this._gptzero(text);
    if (this.provider === 'sapling') return this._sapling(text);
    if (this.provider === 'inhouse') return this._inhouse(text);
    throw new Error(`Unknown detector provider: ${this.provider}`);
  }

  async _inhouse(text) {
    // Uses the in-house detector (OpenAI logprobs + perplexity/burstiness)
    const { detect } = require('./detector');
    const result = await detect(text, this.apiKey, { model: this.model || 'anthropic/claude-opus-4-6' });
    return {
      provider: 'inhouse',
      score: (100 - result.score) / 100, // convert: detector gives 0-100 human, we need 0-1 AI
      human_score: result.score / 100,
      sentences: (result.flagged_sentences || []).map(s => ({
        text: s.text,
        prob: 1 - (s.perplexity / 60), // rough conversion
      })),
      metrics: result.metrics,
    };
  }

  _gptzero(text) {
    const body = JSON.stringify({ document: text });
    const url = new URL('https://api.gptzero.me/v2/predict/text');

    return this._request(url, body, {
      'x-api-key': this.apiKey,
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      const doc = parsed.documents?.[0] || {};
      return {
        provider: 'gptzero',
        score: doc.completely_generated_prob || 0,
        human_score: 1 - (doc.completely_generated_prob || 0),
        sentences: (doc.sentences || [])
          .filter(s => s.generated_prob > 0.7)
          .map(s => ({ text: s.sentence, prob: s.generated_prob })),
      };
    });
  }

  _sapling(text) {
    const body = JSON.stringify({ text });
    const url = new URL('https://api.sapling.ai/api/v1/aidetect');

    return this._request(url, body, {
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      return {
        provider: 'sapling',
        score: parsed.score || 0,
        human_score: 1 - (parsed.score || 0),
        sentences: (parsed.sentence_scores || [])
          .filter(s => s.score > 0.7)
          .map(s => ({ text: s.sentence, prob: s.score })),
      };
    });
  }

  _request(url, body, headers) {
    return new Promise((resolve, reject) => {
      const req = https.request(url, {
        method: 'POST',
        headers: { ...headers, 'Content-Length': Buffer.byteLength(body) },
        timeout: 30000,
      }, res => {
        let data = '';
        res.on('data', c => data += c);
        res.on('end', () => {
          if (res.statusCode >= 400) {
            reject(new Error(`Detector API error ${res.statusCode}: ${data.slice(0, 300)}`));
          } else {
            resolve(data);
          }
        });
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('Detector timeout')); });
      req.write(body);
      req.end();
    });
  }
}

// ============================================================
// TEXT CHUNKING
// ============================================================

function chunkText(text, maxChunk = 3000) {
  const lines = text.split('\n');
  const chunks = [];
  let current = '';
  let inCodeBlock = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      if (current.trim()) {
        chunks.push({ text: current.trim(), type: 'prose' });
        current = '';
      }
      if (!chunks.length || chunks[chunks.length - 1].type !== 'code') {
        chunks.push({ text: line, type: 'code' });
      } else {
        chunks[chunks.length - 1].text += '\n' + line;
      }
      continue;
    }

    if (inCodeBlock) {
      if (chunks.length && chunks[chunks.length - 1].type === 'code') {
        chunks[chunks.length - 1].text += '\n' + line;
      } else {
        chunks.push({ text: line, type: 'code' });
      }
      continue;
    }

    if (trimmed.startsWith('|')) {
      if (current.trim() && !current.trim().split('\n').pop().trim().startsWith('|')) {
        chunks.push({ text: current.trim(), type: 'prose' });
        current = '';
      }
      if (!chunks.length || chunks[chunks.length - 1].type !== 'table') {
        chunks.push({ text: line, type: 'table' });
      } else {
        chunks[chunks.length - 1].text += '\n' + line;
      }
      continue;
    }

    if (current.length + line.length + 1 > maxChunk && current.trim()) {
      chunks.push({ text: current.trim(), type: 'prose' });
      current = '';
    }
    current += line + '\n';
  }
  if (current.trim()) {
    chunks.push({ text: current.trim(), type: 'prose' });
  }
  return chunks;
}

// ============================================================
// PIECE-LEVEL DETECTION & REWRITING
// Break text into paragraphs, score each, only rewrite failures
// ============================================================

function splitParagraphs(text) {
  return text.split(/\n\n+/).map(p => p.trim()).filter(p => p.length > 0);
}

async function hfScore(text, hfToken) {
  const { detect } = require('./detector');
  const r = await detect(text, hfToken, { hf_token: hfToken });
  return { human: r.human_probability, ai: r.ai_probability, score: r.score };
}

// ============================================================
// MAIN HUMANIZE FUNCTION
// Break → Score → Rewrite failures → Reassemble → Re-score → Repeat
// ============================================================

async function humanize(text, options = {}) {
  const llm = new LLMProvider({
    provider: options.llm_provider || 'openrouter',
    apiKey: options.llm_api_key,
    model: options.llm_model,
    baseUrl: options.llm_base_url,
  });

  const hfToken = options.hf_token || process.env.HF_TOKEN;
  const maxRounds = options.max_retries ?? 10;
  const targetHuman = options.target_score ?? 0.98;

  const chunks = chunkText(text, options.max_chunk_size || 3000);
  const results = [];
  const log = [];

  for (let ci = 0; ci < chunks.length; ci++) {
    const chunk = chunks[ci];

    if (chunk.type !== 'prose') {
      results.push(chunk.text);
      log.push({ chunk: ci + 1, type: chunk.type, action: 'passthrough' });
      continue;
    }

    log.push({ chunk: ci + 1, type: 'prose', chars: chunk.text.length });

    // Step 1: Initial full rewrite
    let humanized;
    try {
      humanized = await llm.complete(SYSTEM_PROMPT, chunk.text);
    } catch (err) {
      log.push({ chunk: ci + 1, action: 'llm_error', error: err.message });
      results.push(chunk.text);
      continue;
    }
    log.push({ chunk: ci + 1, action: 'initial_rewrite', output_chars: humanized.length });

    if (!hfToken) {
      log.push({ chunk: ci + 1, action: 'no_hf_token_skip_detection' });
      results.push(humanized);
      continue;
    }

    // Step 2: Score full text first
    let fullScore;
    try {
      fullScore = await hfScore(humanized, hfToken);
    } catch (e) {
      log.push({ chunk: ci + 1, action: 'detection_error', error: e.message });
      results.push(humanized);
      continue;
    }

    log.push({ chunk: ci + 1, round: 0, full_human: Math.round(fullScore.human * 1000) / 1000 });

    if (fullScore.human >= targetHuman) {
      log.push({ chunk: ci + 1, action: 'passed_first_try', human: fullScore.human });
      results.push(humanized);
      continue;
    }

    // Step 3: Break into paragraphs, score each
    for (let round = 1; round <= maxRounds; round++) {
      const paragraphs = splitParagraphs(humanized);
      const scored = [];

      for (let pi = 0; pi < paragraphs.length; pi++) {
        const p = paragraphs[pi];
        if (p.length < 30) {
          scored.push({ idx: pi, text: p, human: 1, ai: 0, pass: true });
          continue;
        }
        try {
          const s = await hfScore(p, hfToken);
          scored.push({ idx: pi, text: p, human: s.human, ai: s.ai, pass: s.human >= 0.85 });
        } catch (e) {
          scored.push({ idx: pi, text: p, human: 0.5, ai: 0.5, pass: true }); // skip on error
        }
      }

      const failing = scored.filter(s => !s.pass).sort((a, b) => a.human - b.human);
      log.push({
        chunk: ci + 1,
        round,
        paragraphs: paragraphs.length,
        failing: failing.length,
        scores: scored.map(s => ({ human: Math.round(s.human * 100), pass: s.pass })),
      });

      if (failing.length === 0) {
        // All paragraphs pass individually — check full text
        const reassembled = scored.map(s => s.text).join('\n\n');
        const fs = await hfScore(reassembled, hfToken);
        log.push({ chunk: ci + 1, round, full_human: Math.round(fs.human * 1000) / 1000 });

        if (fs.human >= targetHuman) {
          humanized = reassembled;
          log.push({ chunk: ci + 1, action: 'passed', human: fs.human });
          break;
        }

        // Full text fails but paragraphs pass — need structural diversity
        if (round <= maxRounds - 1) {
          try {
            humanized = await llm.complete(
              SYSTEM_PROMPT,
              `This text scores ${Math.round(fs.human * 100)}% human. Individual paragraphs pass but the overall text reads as AI because paragraphs share similar rhythm and structure. Rephrase to vary the pacing between paragraphs — some short, some long, different sentence openings. KEEP THE EXACT SAME MEANING AND POINTS. Do NOT add or remove content.

Text:\n\n${reassembled}`,
              0.95
            );
            log.push({ chunk: ci + 1, action: 'structural_diversity_rewrite' });
          } catch (e) {
            log.push({ chunk: ci + 1, action: 'rewrite_error', error: e.message });
            break;
          }
        }
        continue;
      }

      // Rewrite only the failing paragraphs
      const newParagraphs = [...paragraphs];
      for (const fail of failing) {
        const temp = Math.min(0.9 + (round * 0.02), 1.0);
        try {
          let rewritePrompt;
          const MEANING_CONSTRAINT = `CRITICAL: Keep the EXACT same meaning, facts, points, and information. Do NOT add new ideas, tangents, or opinions. Do NOT remove any points. Same message, different words and rhythm. If the original says "React Server Components reduce bundle size" the rewrite MUST say the same thing — just phrased differently.`;

          if (round <= 3) {
            rewritePrompt = `This paragraph scores ${Math.round(fail.human * 100)}% human (needs 85%+). Rewrite with different word choices and sentence rhythm. ${MEANING_CONSTRAINT}

Techniques: swap synonyms, split or merge sentences, reorder clauses within a sentence, vary sentence lengths, swap formal for casual phrasing or vice versa.

Paragraph to rewrite:
${fail.text}`;
          } else if (round <= 7) {
            rewritePrompt = `Rewrite this paragraph with completely different sentence structures and word choices. ${MEANING_CONSTRAINT}

Every sentence must convey the same point as the original but use different vocabulary and pacing. Mix short and long sentences.

${fail.text}`;
          } else {
            rewritePrompt = `Rephrase this paragraph one more time. Different words, different rhythm, same exact content. ${MEANING_CONSTRAINT}

${fail.text}`;
          }
          const rewritten = await llm.complete(SYSTEM_PROMPT, rewritePrompt, temp);
          newParagraphs[fail.idx] = rewritten.trim();
          log.push({ chunk: ci + 1, round, para: fail.idx, action: 'rewrite', from_human: Math.round(fail.human * 100) });
        } catch (e) {
          log.push({ chunk: ci + 1, round, para: fail.idx, action: 'rewrite_error', error: e.message });
        }
      }

      // Reassemble and score full text
      humanized = newParagraphs.join('\n\n');
      try {
        fullScore = await hfScore(humanized, hfToken);
        log.push({ chunk: ci + 1, round, full_human: Math.round(fullScore.human * 1000) / 1000 });
      } catch (e) {
        log.push({ chunk: ci + 1, round, action: 'full_score_error', error: e.message });
        continue;
      }

      if (fullScore.human >= targetHuman) {
        log.push({ chunk: ci + 1, action: 'passed', human: fullScore.human });
        break;
      }

      if (round === maxRounds) {
        log.push({ chunk: ci + 1, action: 'max_rounds', final_human: fullScore.human });
      }
    }

    results.push(humanized);
  }

  const output = results.join('\n\n');

  // Final full-text detection
  let finalDetection = null;
  if (hfToken) {
    try {
      const proseOnly = chunks.reduce((acc, chunk, idx) => {
        if (chunk.type === 'prose') acc += results[idx] + '\n\n';
        return acc;
      }, '').trim();
      finalDetection = await hfScore(proseOnly, hfToken);
    } catch (e) {
      finalDetection = { error: e.message };
    }
  }

  return {
    humanized: output,
    chunks: chunks.length,
    detection: finalDetection,
    log,
  };
}

async function detectOnly(text, config = {}) {
  const detector = new AIDetector({
    provider: config.provider || 'gptzero',
    apiKey: config.apiKey,
  });
  return detector.detect(text);
}

module.exports = { humanize, detectOnly, chunkText, LLMProvider, AIDetector };
