const https = require('https');
const http = require('http');

// ============================================================
// HUMANIZER ENGINE
// Pluggable LLM + AI detection verification loop
// ============================================================

const SYSTEM_PROMPT = `You are a text rewriter. Your job is to rewrite text so it passes AI detection tools like GPTZero, Originality.ai, and Copyleaks as HUMAN-WRITTEN.

These tools detect AI by measuring:
- PERPLEXITY: How predictable each word is. AI picks "safe" high-probability words. Humans use surprising, unexpected, idiosyncratic choices.
- BURSTINESS: Sentence length variation. AI writes uniform-length sentences. Humans alternate wildly — fragments, then long run-ons, then medium.
- TOKEN PATTERNS: AI clusters around statistically expected phrases. Humans deviate.

YOUR REWRITING STRATEGY:

SENTENCE STRUCTURE (critical for burstiness):
1. Make sentence lengths WILDLY inconsistent. Like this. Then write one that goes on for a while with multiple clauses and asides because that's how people actually think when they're working through an idea. Then short again.
2. Use sentence fragments deliberately. Not every thought needs a verb.
3. Start sentences with "And", "But", "So", "Or", "Because" — at least 20% of them.
4. Use questions mid-text. "Why does this matter?" "Who cares?" "Sound familiar?"

WORD CHOICE (critical for perplexity):
5. Replace common/expected words with less obvious synonyms. Not "utilize" → "use", but "important" → "kind of a big deal", "significant" → "massive", "implement" → "wire up", "facilitate" → "make happen".
6. Use colloquialisms, slang, and informal language mixed with technical terms. "The API is solid but the docs are garbage" not "The API is reliable but the documentation could be improved."
7. Use filler words sparingly but naturally: "honestly", "basically", "look", "I mean", "right?"
8. Throw in the occasional oddly specific detail or analogy that an AI wouldn't generate.

STRUCTURAL TRICKS (critical for pattern detection):
9. BREAK parallel structure aggressively. If listing 3 things, format each one differently — one as a sentence, one as a fragment, one as a question.
10. Use parenthetical asides (humans think out loud constantly).
11. Use em dashes — these break up sentence flow unpredictably.
12. Vary paragraph lengths: one-liner, then a chunky paragraph, then a medium one.
13. Use contractions INCONSISTENTLY. Mix "don't" and "do not" within the same piece. Humans are messy about this.

ANTI-DETECTION (what gets caught):
14. NEVER use these phrases (instant AI flag): "It's worth noting", "In today's world", "game-changer", "landscape", "leverage", "comprehensive", "streamline", "robust", "cutting-edge", "delve", "Furthermore", "Moreover", "Consequently", "Nevertheless", "unprecedented", "transformative", "seamlessly", "holistic", "paradigm", "empowering", "fostering innovation", "navigate the complex", "In conclusion", "key takeaway".
15. NEVER use smooth academic transitions between every paragraph. Sometimes just... start the next thought. No bridge needed.
16. NEVER write sentences that all hover around the same length (15-25 words). Mix 3-word sentences with 40-word ones.
17. Avoid ending multiple paragraphs with the same sentence structure.

HARD CONSTRAINTS:
18. Preserve the EXACT meaning, technical accuracy, all links, formatting, and code blocks.
19. Do NOT make the text longer or add fluff/motivational language.
20. CODE BLOCKS must be returned EXACTLY as-is.
21. Keep the author's voice. You're rewriting HOW it's said, not WHAT it says.

Output ONLY the rewritten text. No explanations.`;

const REWRITE_FLAGGED_PROMPT = `The following sentences were flagged as AI-generated by a RoBERTa classifier. This classifier detects statistical patterns in word choice and sentence structure that are typical of LLM output.

To pass detection, the rewritten sentences MUST:
- Use unexpected, low-probability word choices (not the "obvious" next word)
- Have irregular rhythm — mix a 4-word fragment with a 30-word run-on
- Include at least one imperfection: a dash used loosely, a parenthetical aside, a casual "honestly" or "look"
- Avoid smooth logical connectors (no "Furthermore", "Additionally", "This means that")
- NOT start with "So here's the thing" or "Look," or any other single repeated opener

Examples of sentences that PASS detection:
- "Deleted like 4000 files off my phone yesterday. Chaotically. No regrets."
- "The API is solid but honestly the docs are hot garbage and I spent 3 hours on something that should've taken 20 minutes."
- "I know everyone says microservices are the answer but — and maybe this is controversial — a monolith would've shipped this thing in half the time."

Flagged sentences:
{flagged}

Full text:
{text}

Rewrite ONLY the flagged sentences using the style guidance above. Keep everything else identical. Output the full text.`;

// ============================================================
// LLM PROVIDERS
// ============================================================

class LLMProvider {
  constructor(config) {
    this.provider = config.provider || 'openrouter';
    this.apiKey = config.apiKey;
    this.model = config.model;
    this.baseUrl = config.baseUrl;

    if (this.provider === 'openrouter') {
      this.model = this.model || 'anthropic/claude-opus-4-6';
      this.baseUrl = this.baseUrl || 'https://openrouter.ai/api';
    } else if (this.provider === 'openai') {
      this.model = this.model || 'gpt-5.2';
      this.baseUrl = this.baseUrl || 'https://api.openai.com';
    } else if (this.provider === 'anthropic') {
      this.model = this.model || 'claude-sonnet-4-20250514';
      this.baseUrl = this.baseUrl || 'https://api.anthropic.com';
    } else if (this.provider === 'custom') {
      if (!this.baseUrl) throw new Error('baseUrl required for custom provider');
      this.model = this.model || 'default';
    }
  }

  async complete(systemPrompt, userPrompt, temperature = 0.8) {
    if (this.provider === 'anthropic') {
      return this._anthropic(systemPrompt, userPrompt, temperature);
    }
    return this._openai(systemPrompt, userPrompt, temperature);
  }

  _openai(systemPrompt, userPrompt, temperature) {
    const body = JSON.stringify({
      model: this.model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature,
      max_tokens: 4096,
    });

    const url = new URL(this.baseUrl + '/v1/chat/completions');
    return this._request(url, body, {
      'Authorization': `Bearer ${this.apiKey}`,
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      if (parsed.error) throw new Error(parsed.error.message || JSON.stringify(parsed.error));
      return parsed.choices?.[0]?.message?.content || '';
    });
  }

  _anthropic(systemPrompt, userPrompt, temperature) {
    const body = JSON.stringify({
      model: this.model,
      max_tokens: 4096,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
      temperature,
    });

    const url = new URL('https://api.anthropic.com/v1/messages');
    return this._request(url, body, {
      'x-api-key': this.apiKey,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      if (parsed.error) throw new Error(parsed.error.message || JSON.stringify(parsed.error));
      return parsed.content?.[0]?.text || '';
    });
  }

  _request(url, body, headers) {
    return new Promise((resolve, reject) => {
      const mod = url.protocol === 'https:' ? https : http;
      const req = mod.request(url, {
        method: 'POST',
        headers: { ...headers, 'Content-Length': Buffer.byteLength(body) },
        timeout: 120000,
      }, res => {
        let data = '';
        res.on('data', c => data += c);
        res.on('end', () => {
          if (res.statusCode >= 400) {
            reject(new Error(`LLM API error ${res.statusCode}: ${data.slice(0, 500)}`));
          } else {
            resolve(data);
          }
        });
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('LLM request timeout')); });
      req.write(body);
      req.end();
    });
  }
}

// ============================================================
// AI DETECTION
// Supports: gptzero, sapling
// ============================================================

class AIDetector {
  constructor(config = {}) {
    this.provider = config.provider || 'gptzero';
    this.apiKey = config.apiKey;
    this.model = config.model;
  }

  async detect(text) {
    if (this.provider === 'inhouse') return this._inhouse(text);

    if (!this.apiKey) {
      return { score: 0, human_score: 1, sentences: [], skipped: true };
    }

    if (this.provider === 'gptzero') return this._gptzero(text);
    if (this.provider === 'sapling') return this._sapling(text);
    if (this.provider === 'inhouse') return this._inhouse(text);
    throw new Error(`Unknown detector provider: ${this.provider}`);
  }

  async _inhouse(text) {
    // Uses the in-house detector (OpenAI logprobs + perplexity/burstiness)
    const { detect } = require('./detector');
    const result = await detect(text, this.apiKey, { model: this.model || 'anthropic/claude-opus-4-6' });
    return {
      provider: 'inhouse',
      score: (100 - result.score) / 100, // convert: detector gives 0-100 human, we need 0-1 AI
      human_score: result.score / 100,
      sentences: (result.flagged_sentences || []).map(s => ({
        text: s.text,
        prob: 1 - (s.perplexity / 60), // rough conversion
      })),
      metrics: result.metrics,
    };
  }

  _gptzero(text) {
    const body = JSON.stringify({ document: text });
    const url = new URL('https://api.gptzero.me/v2/predict/text');

    return this._request(url, body, {
      'x-api-key': this.apiKey,
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      const doc = parsed.documents?.[0] || {};
      return {
        provider: 'gptzero',
        score: doc.completely_generated_prob || 0,
        human_score: 1 - (doc.completely_generated_prob || 0),
        sentences: (doc.sentences || [])
          .filter(s => s.generated_prob > 0.7)
          .map(s => ({ text: s.sentence, prob: s.generated_prob })),
      };
    });
  }

  _sapling(text) {
    const body = JSON.stringify({ text });
    const url = new URL('https://api.sapling.ai/api/v1/aidetect');

    return this._request(url, body, {
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      return {
        provider: 'sapling',
        score: parsed.score || 0,
        human_score: 1 - (parsed.score || 0),
        sentences: (parsed.sentence_scores || [])
          .filter(s => s.score > 0.7)
          .map(s => ({ text: s.sentence, prob: s.score })),
      };
    });
  }

  _request(url, body, headers) {
    return new Promise((resolve, reject) => {
      const req = https.request(url, {
        method: 'POST',
        headers: { ...headers, 'Content-Length': Buffer.byteLength(body) },
        timeout: 30000,
      }, res => {
        let data = '';
        res.on('data', c => data += c);
        res.on('end', () => {
          if (res.statusCode >= 400) {
            reject(new Error(`Detector API error ${res.statusCode}: ${data.slice(0, 300)}`));
          } else {
            resolve(data);
          }
        });
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('Detector timeout')); });
      req.write(body);
      req.end();
    });
  }
}

// ============================================================
// TEXT CHUNKING
// ============================================================

function chunkText(text, maxChunk = 3000) {
  const lines = text.split('\n');
  const chunks = [];
  let current = '';
  let inCodeBlock = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      if (current.trim()) {
        chunks.push({ text: current.trim(), type: 'prose' });
        current = '';
      }
      if (!chunks.length || chunks[chunks.length - 1].type !== 'code') {
        chunks.push({ text: line, type: 'code' });
      } else {
        chunks[chunks.length - 1].text += '\n' + line;
      }
      continue;
    }

    if (inCodeBlock) {
      if (chunks.length && chunks[chunks.length - 1].type === 'code') {
        chunks[chunks.length - 1].text += '\n' + line;
      } else {
        chunks.push({ text: line, type: 'code' });
      }
      continue;
    }

    if (trimmed.startsWith('|')) {
      if (current.trim() && !current.trim().split('\n').pop().trim().startsWith('|')) {
        chunks.push({ text: current.trim(), type: 'prose' });
        current = '';
      }
      if (!chunks.length || chunks[chunks.length - 1].type !== 'table') {
        chunks.push({ text: line, type: 'table' });
      } else {
        chunks[chunks.length - 1].text += '\n' + line;
      }
      continue;
    }

    if (current.length + line.length + 1 > maxChunk && current.trim()) {
      chunks.push({ text: current.trim(), type: 'prose' });
      current = '';
    }
    current += line + '\n';
  }
  if (current.trim()) {
    chunks.push({ text: current.trim(), type: 'prose' });
  }
  return chunks;
}

// ============================================================
// SENTENCE-LEVEL DETECTION
// Classifies individual sentences to find which ones are flagged
// ============================================================

async function detectSentences(text, hfToken) {
  const { detect } = require('./detector');
  const sentences = text.split(/(?<=[.!?])\s+/).filter(s => s.trim().length > 20);

  // First: check full text score
  const fullResult = await detect(text, hfToken, { hf_token: hfToken });
  if (fullResult.human_probability >= 0.98) {
    return { passed: true, human_score: fullResult.human_probability, flagged: [], fullResult };
  }

  // If not passing, test individual sentences to find the weak ones
  const flagged = [];
  for (const sentence of sentences) {
    try {
      const r = await detect(sentence, hfToken, { hf_token: hfToken });
      if (r.ai_probability > 0.4) { // sentence looks AI-ish
        flagged.push({ text: sentence, ai_score: r.ai_probability, human_score: r.human_probability });
      }
    } catch (e) {
      // Skip sentences that are too short for detection
    }
  }

  return { passed: false, human_score: fullResult.human_probability, flagged, fullResult };
}

// ============================================================
// MAIN HUMANIZE FUNCTION
// With HuggingFace feedback loop for 98%+ human scores
// ============================================================

async function humanize(text, options = {}) {
  const llm = new LLMProvider({
    provider: options.llm_provider || 'openrouter',
    apiKey: options.llm_api_key,
    model: options.llm_model,
    baseUrl: options.llm_base_url,
  });

  const hfToken = options.hf_token || process.env.HF_TOKEN;
  const maxRetries = options.max_retries ?? 12;
  const targetHumanScore = options.target_score ?? 0.98; // 98% human

  const chunks = chunkText(text, options.max_chunk_size || 3000);
  const results = [];
  const log = [];

  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];

    // Pass through non-prose (code, tables)
    if (chunk.type !== 'prose') {
      results.push(chunk.text);
      log.push({ chunk: i + 1, type: chunk.type, action: 'passthrough' });
      continue;
    }

    log.push({ chunk: i + 1, type: 'prose', chars: chunk.text.length });

    // Step 1: Initial rewrite
    let humanized;
    try {
      humanized = await llm.complete(SYSTEM_PROMPT, chunk.text);
    } catch (err) {
      log.push({ chunk: i + 1, action: 'llm_error', error: err.message });
      results.push(chunk.text);
      continue;
    }
    log.push({ chunk: i + 1, action: 'initial_rewrite', output_chars: humanized.length });

    // Step 2: HuggingFace feedback loop
    if (hfToken) {
      for (let retry = 0; retry < maxRetries; retry++) {
        let detection;
        try {
          detection = await detectSentences(humanized, hfToken);
        } catch (err) {
          log.push({ chunk: i + 1, retry, action: 'detection_error', error: err.message });
          break;
        }

        log.push({
          chunk: i + 1,
          retry,
          human_score: Math.round(detection.human_score * 1000) / 1000,
          flagged_count: detection.flagged.length,
          passed: detection.passed,
        });

        // Target met — we're done
        if (detection.passed || detection.human_score >= targetHumanScore) {
          log.push({ chunk: i + 1, action: 'passed', final_human_score: detection.human_score });
          break;
        }

        // Max retries hit
        if (retry === maxRetries - 1) {
          log.push({ chunk: i + 1, action: 'max_retries', final_human_score: detection.human_score });
          break;
        }

        // Step 3: Escalating rewrite strategies
        try {
          const prevScore = detection.human_score;
          
          if (detection.flagged.length > 0) {
            // Strategy A: Targeted rewrite of flagged sentences
            const flaggedList = detection.flagged
              .sort((a, b) => b.ai_score - a.ai_score)
              .slice(0, 5)
              .map(s => `- "${s.text}" (${Math.round(s.ai_score * 100)}% AI)`)
              .join('\n');

            const prompt = REWRITE_FLAGGED_PROMPT
              .replace('{flagged}', flaggedList)
              .replace('{text}', humanized);
            humanized = await llm.complete(SYSTEM_PROMPT, prompt, 0.9 + (retry * 0.015));
            log.push({ chunk: i + 1, action: 'targeted_rewrite', flagged: detection.flagged.length });

          } else if (retry < 4) {
            // Strategy B: Style rewrite — add personality
            humanized = await llm.complete(
              SYSTEM_PROMPT,
              'This text scores ' + Math.round(detection.human_score * 100) + '% human but needs 98%+. The AI classifier detects uniform statistical patterns in the OVERALL text even though individual sentences pass. Make it messier — interrupt yourself mid-thought, add a random aside, use a run-on sentence, throw in something oddly specific. DO NOT add fluff or length. Just make the rhythm more chaotic and human:\n\n' + humanized,
              0.95
            );
            log.push({ chunk: i + 1, action: 'style_rewrite' });

          } else if (retry < 8) {
            // Strategy C: Nuclear — full rewrite from scratch using original input
            humanized = await llm.complete(
              SYSTEM_PROMPT,
              'COMPLETELY rewrite this from scratch. Same meaning, totally different words and structure. Write it like you\'re explaining it to a friend over coffee — messy, casual, with tangents and personality. Temperature: chaotic. The previous version kept scoring as AI-generated, so you CANNOT reuse the same phrases or patterns:\n\n' + chunk.text,
              0.98
            );
            log.push({ chunk: i + 1, action: 'nuclear_rewrite' });

          } else {
            // Strategy D: Last resort — rewrite as stream of consciousness
            humanized = await llm.complete(
              'You are rewriting text to sound like a real person\'s internal monologue typed out in a Slack message. Use sentence fragments. Start sentences with conjunctions. Include parenthetical asides. Make it feel unpolished and authentic. Vary sentence length between 3 words and 40 words. Output ONLY the rewritten text.',
              'Rewrite this, same core ideas but totally unpolished human voice:\n\n' + chunk.text,
              1.0
            );
            log.push({ chunk: i + 1, action: 'stream_of_consciousness_rewrite' });
          }
        } catch (err) {
          log.push({ chunk: i + 1, action: 'rewrite_error', error: err.message });
          break;
        }
      }
    } else {
      log.push({ chunk: i + 1, action: 'no_hf_token_skip_detection' });
    }

    results.push(humanized);
  }

  const output = results.join('\n\n');

  // Final full-text detection score
  let finalDetection = null;
  if (hfToken) {
    try {
      const { detect } = require('./detector');
      const proseOnly = chunks.reduce((acc, chunk, idx) => {
        if (chunk.type === 'prose') acc += results[idx] + '\n\n';
        return acc;
      }, '').trim();
      finalDetection = await detect(proseOnly, hfToken, { hf_token: hfToken });
    } catch (e) {
      finalDetection = { error: e.message };
    }
  }

  return {
    humanized: output,
    chunks: chunks.length,
    detection: finalDetection,
    log,
  };
}

async function detectOnly(text, config = {}) {
  const detector = new AIDetector({
    provider: config.provider || 'gptzero',
    apiKey: config.apiKey,
  });
  return detector.detect(text);
}

module.exports = { humanize, detectOnly, chunkText, LLMProvider, AIDetector };
